### ISSUE TITLE
suggest: jsx's close tag name can optional?

### ISSUE THREAD

**Issue by xp44mm** [facebook/jsx#107]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
```html
<div>
  <p>some text</p>
  <hr/>
</div>
```

**What is the expected behavior?**
because the html tag always pairs, so if simple write better?
```html
<div>
  <p>some text</>
  <p>some text</p>
  <hr/>
</>
```
it means that the close tag can be `</>` also can be `</p>`.

**Comment by nojvek** [comment]
This would conflict with jsx fragment syntax i.e `<> .... </>`. The definition of `</>` would be overloaded right?

```
<div><p>some text</><></></>
```

Is this ^ more readable than ?

````
<div><p>some text</p><></></div>
```

**Comment by Huxpro** [comment]
Personally I felt like we wouldn't pursue in this direction. Feel free to reopen if any one has a strong second opinion on this.
