### ISSUE TITLE
Is scheme for JSXIdentifier correct?

### ISSUE THREAD

**Issue by igoradamenko** [facebook/jsx#113]
```
JSXIdentifier :
- IdentifierStart
- JSXIdentifier IdentifierPart
- JSXIdentifier NO WHITESPACE OR COMMENT `-`
```

Hey guys,

I'm looking at the scheme above and can't understand one thing. Is it possible according to this spec to create a JSXElement with a JSXElementName such as `$-`?

I'm asking because it looks pretty strange. It's impossible to create such function in JS, and also it's impossible to create such DOM element (I've tried to eval `document.createElement('$-')` and got an error). So, why is it possible to do such things in JSX?

I understand that:

> This specification does not attempt to comply with any XML or HTML specification. JSX is designed as an ECMAScript feature and the similarity to XML is only for familiarity.

But according to usual application of JSX (rendering JS objects to HTML markup) a possibility of things like that is confusing.

(BTW, maybe this issue is related to #29)

**Comment by dantman** [comment]
Yes it does appear that way, I expect that is a mistake. I have a feeling that this is actually supposed to be something like:

> - JSXIdentifier **NO WHITESPACE OR COMMENT** `-` **NO WHITESPACE OR COMMENT** JSXIdentifier

To cover support for `<custom-element>`.

**Comment by j-f1** [comment]
For what it’s worth, Babel [parses `$-$` just fine](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DwEgtCAED0B8Q&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=react&prettier=true&targets=&version=7.0.0-beta.4&envVersion=).

**Comment by igoradamenko** [comment]
@j-f1, it does. But it make no sense later, because it's not a valid name for JS function, and it's not a valid name for HTML tag. So, React obviously can't find a function with this name, and when it tries to evaluate `document.createElement` it fails, because it isn't a valid HTML: https://codesandbox.io/s/937wrr6xny.

I'm not sure is it fine or not, and my question was exactly about it. It looks like it's possible in JSX, but it doesn't possible anywhere else, and for me scheme like this looks meaningless, but maybe I'm wrong.

**Comment by RReverser** [comment]
Don't forget that JSX spec is not intended just for React, and other implementations might have other ways to transpile tag names, making any of these names valid.

**Comment by igoradamenko** [comment]
@RReverser, yes. But JSX is intended for JS & HTML, isn't it?

I mean, yes, I understand that it's actually possible for example to transpile `$-$` into something like `__DOLLARSIGN__HYPHENSIGN__DOLLARSIGN__` and to hope that there won't be any conflicts with user's functions names in future. But I don't see any ways to transpile things like this into something compatible with JS and HTML at the same time and _without_ any future conflicts.

So that was the reason why I created this issue. I think it's better to decrease possible variations of `JSXIdentifier`, to make spec compatible with JS and HTML right now and to prevent a possibility of things like `$-$`. 

For example:
```
JSXElementName :
- IdentifierName
- JSXTagName
- JSXNamespacedName
- JSXMemberExpression

JSXTagName :
- UnicodeIDStart
- JSXTagName NO WHITESPACE OR COMMENT `-`

JSXNamespacedName :
- JSXIdentifier `:` JSXIdentifier

JSXMemberExpression :
- JSXIdentifier `.` JSXIdentifier
- JSXMemberExpression `.` JSXIdentifier
```

Here I removed `JSXIdentifier NO WHITESPACE OR COMMENT -` part from JSXIndentifier, which made it useless as entity, so I changed JSXIdentifier inside JSXElementName to [IdentifierName](https://www.ecma-international.org/ecma-262/8.0/index.html#prod-IdentifierName). And I defined JSXTagName, which can be [UnicodeIDStart](https://www.ecma-international.org/ecma-262/8.0/index.html#prod-UnicodeIDStart) ([Unicode subset](https://unicode.org/cldr/utility/list-unicodeset.jsp?a=[:ID_Start=Yes:])) or `JSXTagName NO WHITESPACE OR COMMENT -` (to support custom HTML tags).

Diff:

```diff
--- previous	2018-12-25 14:33:55.000000000 +0200
+++ next	2018-12-25 14:33:59.000000000 +0200
@@ -1,12 +1,12 @@
 JSXElementName :
-- JSXIdentifier
+- IdentifierName
+- JSXTagName
 - JSXNamespacedName
 - JSXMemberExpression

-JSXIdentifier :
-- IdentifierStart
-- JSXIdentifier IdentifierPart
-- JSXIdentifier NO WHITESPACE OR COMMENT `-`
+JSXTagName :
+- UnicodeIDStart
+- JSXTagName NO WHITESPACE OR COMMENT `-`

 JSXNamespacedName :
 - JSXIdentifier `:` JSXIdentifier
```

**Comment by RReverser** [comment]
It is for JS but it doesn't need to translate to JS identifiers - it's common to transpile it to `someFunc('elemName', ...)`.

**Comment by Huxpro** [comment]
Unless there is anything new, I think this has been desired. Closed.
