### ISSUE TITLE
Allow Expression inside expression container

### ISSUE THREAD

**Issue by RReverser** [facebook/jsx#17]
Subject to discuss as per facebook/react#2143.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by Huxpro** [comment]
Personally I agree with @sebmarkbage and @syranide that allowing `Expression` is unwanted. Closed but feel free to reopen though.
