### ISSUE TITLE
Tool list

### ISSUE THREAD

**Issue by prettydiff** [facebook/jsx#24]
It would be a good idea to indicate a list of tools that provide support for JSX until JSX as a format becomes ubiquitous. There is a serious hesitation to adopt JSX out of fear for tooling support. For instance I know there is a fork of JSHint that supports JSX and a beautifier that fully supports JSX, but these tools are not commonly known or easy to search for.

It would also be a good idea to ask users to submit tools, libraries, packages, and other supporting software. Contributions from the community are a great way to determine where the support is and how to better evangelize this format outside of React.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by Huxpro** [comment]
> until JSX as a format becomes ubiquitous.

From a nowadays standard I think it kinda already does? 😛
