### ISSUE TITLE
Consider including difference between <tag> and <Component> in spec

### ISSUE THREAD

**Issue by glenjamin** [facebook/jsx#29]
This arose in relation to https://github.com/eslint/eslint/issues/1911

Currently, the spec has a single node type for JSXElementName, which separates three cases: identifier, xml-namespaced identifier, JS member expression identifier.

In the implementation as of 0.12, the semantics of a tag differ depending on the casing of the first character of the identifier.

Could this be incorporated in some way? Perhaps as `JSXComponent` vs `JSXIdentifier` or `JSXIdentifier` vs `JSXTag`. Something to indicate that one should be interpreted as a variable reference, and one as a string literal.

**Comment by sebmck** [comment]
The JSX spec purposely doesn't define semantics. It's meant to be agnostic and `<Component>` does not necessarily have to reference a variable.

**Comment by glenjamin** [comment]
In practice, JSX implementations which are "React-agnostic" currently special-case the <tag> forms.

While this remains unspecified, core tooling like eslint & babel are in a bit of a halfway house where React-specific semantics around variables are hard-coded, but not the resulting transform.

**Comment by sebmck** [comment]
@glenjamin Babel isn't a valid comparison since it specifically targets the React flavour of JSX.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by Huxpro** [comment]
Closed because this is intentional.
