### ISSUE TITLE
Prior art: Opa

### ISSUE THREAD

**Issue by hbbio** [facebook/jsx#31]
See for instance https://github.com/MLstate/opalang/wiki/Reference-card#xhtml and generally at http://opalang.org

Opa is an open source project available since 2011.

**Comment by spicyj** [comment]
JSX is based off of XHP, an extension created by Facebook to PHP, which was announced in 2010:

https://www.facebook.com/notes/facebook-engineering/xhp-a-new-way-to-write-php/294003943919

**Comment by jordwalke** [comment]
Also, JSX is essentially the syntax of the `e4x`, which dates back to 2008 IIRC.
BTW: OPA is really cool. You may have recalled me discussing on the message boards how it would be nice to have more control over what the xml style syntax in OPA is parsed as. That never really amounted to anything though.
