### ISSUE TITLE
Consider Switching the ESTree AST Extension to use JSXText instead of Literal

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/jsx#50]
https://github.com/jquery/esprima/issues/1467

Apparently people seem to be in defacto agreement on this.

cc @RReverser

**Comment by vjeux** [comment]
I did a quick survey of parsers using which and it looks like all the major ones are using JSXText, so I would encourage updating the spec for it.

JSXText:
- babylon
- flow
- esprima

JsxText:
- typescript

Literal:
- acorn
- babel-eslint

**Comment by RReverser** [comment]
It could have been helpful to send issues or PRs to other parsers for interop ;)
