### ISSUE TITLE
Wrong hyperlink to E4X

### ISSUE THREAD

**Issue by nickdeis** [facebook/jsx#56]
Hey All,
The hyperlink on the page redirects to the _ECMA-375:   Case for 120 mm HVD-ROM disk_ probably due to 357 having a "withdrawn" status.
[Here's a pdf of the standard](http://www.ecma-international.org/publications/files/ECMA-ST-WITHDRAWN/Ecma-357.pdf)

**Comment by Huxpro** [comment]
Seems like this has been fixed. Closed.
