### ISSUE TITLE
provide `this` context in SFCs when they are invoked via `JSXMemberExpression`

### ISSUE THREAD

**Issue by Artazor** [facebook/jsx#69]
**[holy-war question alert!]** copied from https://github.com/facebook/react/issues/8714

Would it be possible to provide `this` context into SFCs when they are invoked via 
`JSXMemberExpression . JSXIdentifier` syntactic form?

My use-case involves unusual ES6 class usage. I'm using them as inheritable containers for SFC's, where individual components could be overridden in descendant classes.

Now I'm forced to autobind all view-methods:

```jsx
class Base {
    constructor() {
        // would like to avoid these:
        this.Short = this.Short.bind(this);
        this.Full = this.Full.bind(this);
    }
   Short() { return <span>{`${this}`}</span>; }
   Full() { return <div><this.Short /></div>; }
}

class Item extends Base {
    constructor(value) {
        super();
        this.value = value;
    }
    toString() {
        return this.value;
    }
}

var obj = new Item("A");
ReactDOM.render(<obj.Full />, document.getElementById("container"));
```

A bit more complete example could be found at: https://jsfiddle.net/69z2wepo/67046/

I understand that it is a Holy War question about pure functions and `this` in JavaScript.
However I'm thinking that this usage of `this` is legit. Just like a `children` in props.

It is way too ugly writing:
```jsx
class Base {
   Short({self}) { return <span>{`${self}`}</span>; }
   Full({self}) { return <div><self.Short self={self} /></div>; }
}

class Item extends Base {
    constructor(value) {
        super();
        this.value = value;
    }
    toString() {
        return this.value;
    }
}

var obj = new Item("A");
ReactDOM.render(<obj.Full self={obj} />, document.getElementById("container"));
```
Isn't it?

---

I even would be happy if
```jsx
<a.b.c />
```
 would be treated as
```jsx
<a.b.c self={a.b} />
``` 
just like `children` - provide some special member in props. However it could be problematic as it will clash with existing user code.

**Comment by sebmarkbage** [comment]
This is not something that is within the scope of this JSX spec since it is already expressable in the syntax form that this spec provides. Everything about the actual semantics is defined by each library. Therefore the issue on the React repo was the correct place to have the discussion.
