### ISSUE TITLE
Proposal: Need of some MVC architecture.

### ISSUE THREAD

**Issue by ashokkumarsand** [facebook/jsx#72]
The rendering javascript with the HTML is too complex. And classes are too complex with the many methods. If we have annotations, like initialization of the application. Run time props injections. 
Also accessibility support. Key event support @click, @keydown,  @load, @render, @mount, @unmount, @component, @model and etc.

In the rendering of component call many times of render() method, It needs some lazy rendering technique which can calculate all change after that it apply in render().
Binding state to props is also a very bad approach

**Comment by ashokkumarsand** [comment]
`@Template("<MyComponent attribute1=""/>")
class Mew {
  //code
  @render
  render(@inject state) {
  // write your extra jsx here
  }
}
`

**Comment by sebmarkbage** [comment]
Seems more like a suggestion for another library, [decorators](https://github.com/tc39/proposal-decorators) or both. I'm going to close this out since I don't see anything directly actionable to the JSX spec (which can be used by any MVC architecture, or not).
