### ISSUE TITLE
[Feature Request]: Provision for style/external styles

### ISSUE THREAD

**Issue by ashokkumarsand** [facebook/jsx#73]
In JSX we can only apply styles in JSON object. There is some provision required, So user can also apply classes with attribute selector and other selectors
`static style() {
    <style>
      [#/./name][attribute="value"][ |: pseudo| :: pseudo] {
        border: 1px solid #efefef;
      }  
    </style>
}`

**Comment by borela** [comment]
Use CSS modules.

**Comment by ashokkumarsand** [comment]
@borela CSS module doesn't support the attribute selector

**Comment by borela** [comment]
Yes it does, CSS modules are just normal CSS classes. For everything else just use the [:global switch](https://github.com/css-modules/css-modules#exceptions).

**Comment by ashokkumarsand** [comment]
@borela But If we get in built react then there is no need to add third party api or library. currently we are using css module. but for large application that is bad pattern.

**Comment by ashokkumarsand** [comment]
For example i want to apply style with nth selector then what happen.

**Comment by borela** [comment]
With the [global switch you can do that](https://github.com/ctrine/react-ui-theme/blob/master/carbon/src/button/base.mscss#L30). As for the bad pattern, I disagree, my components has their CSS module in the same directory for example:

```
login
   index.js
   style.mcss
list-of-users
  index.js
  style.mcss
```

I use `mscss` extension to identify css modules in webpack. That way I can have easily 1000+ components without major headches.

**Comment by ashokkumarsand** [comment]
@borela The issue which i facing is different. I am doing this with china-logic. But if we have attribute selector then that is very helpful. 
Thanks for you assistance

**Comment by ashokkumarsand** [comment]
@facebook-github-bot  **I Think is that meaning of JSX is JavaScript + Styles + XHTML then it complete meaning**

**Comment by sebmarkbage** [comment]
This JSX repo is a spec for the syntax definition of JSX and not for an implementation of React or any other library that might want to utilize this syntax.

The syntax that you describe is already covered by the JSX *syntax* specification, but not by React. You can open it up on React if you're interested in discussing any compatibility issues. Although what you're describing is also supported by React, you just have to make sure it gets rendered into a tree. If that tree is a shadow DOM it is also local to that subtree.

**Comment by sebmarkbage** [comment]
Actually I think what you're really asking for is a dupe of https://github.com/facebook/jsx/issues/74

**Comment by ashokkumarsand** [comment]
@sebmarkbage The JSX syntax also having some provision for STYLE because without style Web development is in complete. IF JSX syntax having provision for Javascript with HTML/XHTML then it also have same tags for STYLE also, and from my perspective its incomplete.
